export enum TypeFunMath{
    MATHABS,
    MATHCEIL,
    MATHFLOOR,
    MATHROUND,
    MATHMAX,
    MATHMIN,
    MATHPOW,
    MATHSQRT,
    MATHRANDOM,
    MATHTORADIANS,
    MATHACOS,
    MATHSIN,
    MATHATAN,
    MATHEXP
}